
cmds = {
"KSA":	"dBm",
"KSB":	"dBmV",
"KSC":	"dBuV",
"KSD":	"V",
"KSE":	"TITLE",
"KSF":	("Shift YFO by IF", "Measure sweep time"),
"KSG":	"Video Averaging on",
"KSH":	"Video Averaging off",
"KSI":	"Extend RefLev to +60dBm",
"KSJ":	"Manual DAC control",
"KSK":	("Move marker next highest peak", "Counts pilot IF at the marker"),
"KSL":	"Turn off avg noise marker",
"KSM":	"Avg amp at marker 1Hzbw",
"KSN":	("Move marker to min val", "Counts VCO at marker"),
"KSO":	"Move marker dF int freq span",
"KSP":	"Set HP-IP addr",
"KSQ":	("Unlock freq band", "Counts signal IF"),
"KSR":	"Truns freq diag on",
"KSS":	("Fast HP-IB format", "Auto 2nd LO freq"),
"KST":	("Fast preset 2-22GHz", "Shift 2nd LO down"),
"KSU":	("Ext mixer preset", "Shoft 2nd LO up"),
"KSV":	"Frequency offset",
"KSW":	"Perform Autocal",
"KSX":	"Use Autocal",
"KSY":	"Unuse Autocal",
"KSZ":	"RefLev offset",
"KSa":	"Normal detector",
"KSb":	"Peak+ detector",
"KSc":	"A=A+B",
"KSd":	"Peak- detector",
"KSe":	"Sample detector",
"KSf":	"Recover last state",
"KSg":	"Turn CRT off",
"KSh":	"Turn CRT on",
"KSi":	"B<-->C",
"KSj":	"View C",
"KSk":	"Blank C",
"KSl":	"B->C",
"KSm":	"Graticule off",
"KSn":	"Graticule on",
"KSo":	"Annotation off",
"KSp":	"Annotation on",
"KSq":	"Decouple IF gain/RF atten",
"KSr":	"SRQ 102",
"KSt":	("Lock freq band", "Continues sweep from marker"),
"KSu":	"Stop sweep at marker in single mode",
"KSv":	("Ident sign for ext mixing freq bands", "Inhibit phase lock"),
"KSw":	"Display Autocal data",
"KSx":	"Trig=ext -auto-refresh",
"KSy":	"Trig=video -auto-refresh",
"KSz":	"Display storage address",
"KS,":	"Mixer level",
"KS=":	("Factor preselector setting", "Resolution of marker FreqCnt"),
"KS(":	"Locks save registers",
"KS)":	"Unlocks save registers",
"KS|":	"See DW",
"KS>":	(None, "Preamp gain input2"),
"KS<":	(None, "Preamp gain input1"),
"KS#":	("YTX self heating correction off", None),
"KS/":	("Manual preselector peaking", None),
"KS9":	"Write display fast binary",
"KS+":	"Set SRQ 102 when freq limit exceeded",
"KS[":	"Return amplitude error",
"KS\\":	"Set marker in binary (DL|TH|M2|M3 prefix)",
"KS^":	"Return code for harmonic number in binary",
"KS}":	"Write display in binary (DA prefix)",
"KS~":	"Return every Nth value of trace (O1|O2|O3|O4+DA prefix)",
"KS\177":	"Display write binary with length (DA prefix)",
"OL":	"Returns the coded instrument state information in 80 8-bit bytes",
}
